name: Syncriix
avatar: images/profile.jpg # Avatar image. Default to "images/profile.webp".
bio: 'Hacker & AI Enthusiast'
company: Contact2Hire # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Earth # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://e2tc.netlify.app # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
# See https://e2tc.netlify.app//v1/en/docs/widgets/social-links/.
social:
  email: syncriix@pm.me
  github: syncriix
  twitter: syncriix
  patreon: syncriix
  paypal: syncriix
  rss: "" # Remove RSS
