# See https://e2tc.netlify.app//v1/en/docs/widgets/social-links/.
email: syncriix@pm.me
github: syncriix
instagram: yourinstagramusername
discord: yourdiscordinvitecode
paypal: syncriix
patreon: syncriix
